-- Seed data for the todo app database
-- This will create test users, projects, tasks, and subtasks

-- Clean up existing data
DELETE FROM tasks;
DELETE FROM projects;
DELETE FROM passwords;
DELETE FROM users;

-- Create test user
INSERT INTO users (id, email, name, role, created_at, updated_at)
VALUES ('user_1', 'demo@example.com', 'Demo User', 'demo', current_timestamp, current_timestamp);

INSERT INTO passwords (user_id, hash)
VALUES ('user_1', '$2a$10$zxUtTd7PI33/tbXv0eGYvOAFAcgpZBhB1ArKgZ9LDpDEzCHJBgix2');

-- Create projects
INSERT INTO projects (id, user_id, title, description, priority, target_date, completed_at, created_at, updated_at) 
VALUES 
('proj_001', 'user_1', 'Website Redesign', 'A comprehensive website redesign project focused on improving user experience, updating the visual design, and implementing modern web technologies. This project involves multiple phases including research, design, development, and deployment to transform our outdated website into a responsive and accessible platform.', 'high', '2025-12-25', NULL, current_timestamp, current_timestamp),
('proj_002', 'user_1', 'Mobile App Development', 'Development of a cross-platform mobile application for both iOS and Android using React Native. The app will include user authentication, real-time data synchronization, push notifications, and offline functionality. This project aims to provide a seamless mobile experience for our customers to access our services on the go.', 'medium', '2025-09-15', NULL, current_timestamp, current_timestamp),
('proj_003', 'user_1', 'Database Migration', 'A critical infrastructure project to migrate our legacy database system to a modern, scalable solution. This migration includes data transformation, validation, and verification while ensuring minimal downtime. The project will improve query performance, data integrity, and enable more robust analytics capabilities for our growing business needs.', 'high', '2025-07-30', NULL, current_timestamp, current_timestamp),
('proj_004', 'user_1', 'API Integration', 'Integration project connecting our systems with third-party services and partners through standardized APIs. This includes implementing authentication mechanisms, rate limiting, data transformation, and comprehensive error handling to ensure reliable communication between systems and enhance our product offering with external functionality.', 'low', NULL, '2025-02-15', current_timestamp, current_timestamp),
('proj_005', 'user_1', 'Dashboard Analytics', 'Development of an interactive analytics dashboard that visualizes key business metrics and performance indicators. This project includes data aggregation from multiple sources, custom visualization components, and user-configurable views to help stakeholders make data-driven decisions and monitor business health in real-time.', 'medium', '2025-11-01', NULL, current_timestamp, current_timestamp);

-- Project 1: Website Redesign - Tasks
INSERT INTO tasks (id, project_id, parent_task_id, title, description, label, priority, target_date, completed_at, created_at, updated_at) 
VALUES 
('task_101', 'proj_001', NULL, 'Research and Planning', 'Conduct comprehensive market research, user interviews, and competitive analysis to inform the website redesign strategy. This includes creating user personas, defining key user journeys, and establishing project goals and success metrics to guide the redesign process.', 'research', 'high', '2025-07-15', NULL, current_timestamp, current_timestamp),
('task_102', 'proj_001', NULL, 'Design System', 'Create a cohesive design system including color palettes, typography, component library, and design tokens to ensure consistency across the website. This system will serve as the foundation for all UI elements and provide guidelines for future design additions.', 'design', 'medium', '2025-08-01', NULL, current_timestamp, current_timestamp),
('task_103', 'proj_001', NULL, 'Frontend Development', 'Implement the new website design using modern frontend technologies such as React, TypeScript, and CSS-in-JS. Create responsive layouts, interactive components, and ensure cross-browser compatibility for an optimal user experience on all devices and platforms.', 'development', 'high', '2025-09-15', NULL, current_timestamp, current_timestamp),
('task_104', 'proj_001', NULL, 'Backend Development', 'Develop server-side functionality to support the website features including APIs, data processing, and integration with existing systems. Implement proper error handling, logging, and security measures to ensure a robust backend infrastructure.', 'development', 'high', '2025-10-01', NULL, current_timestamp, current_timestamp),
('task_107', 'proj_001', NULL, 'Testing and QA', 'Conduct thorough testing including unit tests, integration tests, UI tests, and manual QA to identify and fix issues. Create testing scenarios for critical user flows and ensure all features function correctly across different browsers and devices.', 'testing', 'medium', '2025-11-15', NULL, current_timestamp, current_timestamp);

-- Project 1: Website Redesign - Subtasks
INSERT INTO tasks (id, project_id, parent_task_id, title, description, label, priority, target_date, completed_at, created_at, updated_at) 
VALUES 
-- Subtasks for Research and Planning
('task_101_1', 'proj_001', 'task_101', 'Review components', 'Evaluate existing website components and identify which ones can be reused, which need to be redesigned, and which should be eliminated in the new website architecture. Document component functionality and integration points to inform the design system creation.', 'research', 'medium', '2025-07-05', NULL, current_timestamp, current_timestamp),
('task_101_2', 'proj_001', 'task_101', 'Create workflow', 'Establish project workflows including design approval processes, development methodologies, code review procedures, and communication channels to ensure efficient collaboration across teams throughout the website redesign project.', 'research', 'high', '2025-07-10', NULL, current_timestamp, current_timestamp),
('task_101_3', 'proj_001', 'task_101', 'Document process', 'Create comprehensive documentation of the research findings, strategic recommendations, and project approach. Include user research insights, technical requirements, and project timelines to serve as a reference throughout the redesign process.', 'documentation', 'low', '2025-07-12', NULL, current_timestamp, current_timestamp),

-- Subtasks for Frontend Development
('task_103_1', 'proj_001', 'task_103', 'Implement components', 'Develop reusable frontend components based on the design system specifications using React and TypeScript. Ensure components are properly tested, accessible, and follow best practices for performance and maintainability.', 'development', 'high', '2025-08-20', NULL, current_timestamp, current_timestamp),
('task_103_2', 'proj_001', 'task_103', 'Test functionality', 'Write and execute tests for frontend components and user interactions to ensure proper functionality across browsers and devices. Implement both automated unit tests and integration tests to verify component behavior and page flows.', 'testing', 'medium', '2025-09-01', NULL, current_timestamp, current_timestamp),
('task_103_3', 'proj_001', 'task_103', 'Optimize performance', 'Analyze and improve frontend performance by implementing code splitting, lazy loading images, optimizing bundle size, and utilizing browser caching. Monitor key performance metrics and implement improvements to achieve optimal page load times and interaction responsiveness.', 'development', 'medium', '2025-09-10', NULL, current_timestamp, current_timestamp);

-- Project 2: Mobile App Development - Tasks
INSERT INTO tasks (id, project_id, parent_task_id, title, description, label, priority, target_date, completed_at, created_at, updated_at) 
VALUES 
('task_201', 'proj_002', NULL, 'UI/UX Design', 'Create a comprehensive and intuitive user interface design for the mobile application that adheres to platform design guidelines for both iOS and Android. Develop user flows, wireframes, and high-fidelity mockups that emphasize usability and provide a seamless experience across different device sizes and orientations.', 'design', 'high', '2025-07-15', NULL, current_timestamp, current_timestamp),
('task_202', 'proj_002', NULL, 'Core Functionality Development', 'Implement the core features and functionality of the mobile application including data management, business logic, API integration, and offline capabilities. This task covers the development of the app''s primary screens and components using React Native to ensure consistent behavior across iOS and Android platforms.', 'development', 'high', '2025-08-15', NULL, current_timestamp, current_timestamp),
('task_203', 'proj_002', NULL, 'Testing and Deployment', 'Conduct thorough testing of the mobile application across multiple devices and OS versions, including unit tests, integration tests, and user acceptance testing. Address all identified bugs and issues before preparing the final builds for submission to the Apple App Store and Google Play Store.', 'testing', 'high', '2025-09-15', NULL, current_timestamp, current_timestamp);

-- Project 2: Mobile App Development - Subtasks
INSERT INTO tasks (id, project_id, parent_task_id, title, description, label, priority, target_date, completed_at, created_at, updated_at) 
VALUES 
('task_201_1', 'proj_002', 'task_201', 'User Research', 'Conduct user research through interviews, surveys, and competitive analysis to identify user needs, preferences, and pain points. Create user personas and journey maps to guide the design process and ensure the application addresses actual user requirements.', 'research', 'high', '2025-07-01', NULL, current_timestamp, current_timestamp),
('task_201_2', 'proj_002', 'task_201', 'Wireframing', 'Create detailed wireframes for all application screens showing layout structure, navigation patterns, and content hierarchy. Develop low-fidelity prototypes to test user flows and iterate based on internal stakeholder feedback before moving to high-fidelity designs.', 'design', 'medium', '2025-07-07', NULL, current_timestamp, current_timestamp),
('task_201_3', 'proj_002', 'task_201', 'Visual Design', 'Develop the final visual design for the application including color schemes, typography, iconography, and component styles. Create a consistent design language that follows platform guidelines while maintaining brand identity across both iOS and Android versions.', 'design', 'high', '2025-07-15', NULL, current_timestamp, current_timestamp),
('task_202_1', 'proj_002', 'task_202', 'Authentication System', 'Implement a secure authentication system including login, registration, password reset, and session management. Integrate with OAuth providers and implement biometric authentication options while ensuring proper security measures and token handling.', 'development', 'high', '2025-07-25', NULL, current_timestamp, current_timestamp),
('task_202_2', 'proj_002', 'task_202', 'Data Management', 'Develop the data layer of the application including local storage, caching mechanisms, and synchronization with backend services. Implement efficient state management using Redux or Context API and handle offline functionality with proper conflict resolution.', 'development', 'high', '2025-08-05', NULL, current_timestamp, current_timestamp),
('task_202_3', 'proj_002', 'task_202', 'Push Notifications', 'Integrate push notification services for both iOS and Android platforms. Implement notification handling for different application states (foreground, background, terminated) and create a notification preference center for users to manage their notification settings.', 'development', 'medium', '2025-08-15', NULL, current_timestamp, current_timestamp),
('task_203_1', 'proj_002', 'task_203', 'Automated Testing', 'Implement comprehensive automated testing suite including unit tests for business logic, component tests for UI elements, and end-to-end tests for critical user flows. Set up continuous integration to run tests automatically on code changes to maintain code quality.', 'testing', 'high', '2025-08-25', NULL, current_timestamp, current_timestamp),
('task_203_2', 'proj_002', 'task_203', 'Beta Testing', 'Distribute beta versions of the application to a selected group of users for real-world testing. Collect feedback, analyze usage patterns, and identify bugs or usability issues before the official release to ensure the application meets user expectations.', 'testing', 'medium', '2025-09-05', NULL, current_timestamp, current_timestamp),
('task_203_3', 'proj_002', 'task_203', 'App Store Submission', 'Prepare application builds for submission to Apple App Store and Google Play Store. Create store listings including screenshots, feature descriptions, and metadata. Address any review feedback and ensure compliance with platform guidelines and requirements.', 'deployment', 'high', '2025-09-15', NULL, current_timestamp, current_timestamp);

-- Add similar tasks for Project 3, 4, 5...
INSERT INTO tasks (id, project_id, parent_task_id, title, description, label, priority, target_date, completed_at, created_at, updated_at) 
VALUES 
-- Project 3: Database Migration - Basic tasks
('task_301', 'proj_003', NULL, 'Research and Planning', 'Analyze the existing database architecture, identify pain points, and establish migration requirements. Evaluate different database technologies, create a detailed migration strategy, and define success criteria while considering business constraints such as downtime limitations and data integrity requirements.', 'research', 'high', '2025-06-10', NULL, current_timestamp, current_timestamp),
('task_302', 'proj_003', NULL, 'Data Modeling', 'Design the new database schema incorporating best practices for performance, scalability, and data integrity. Create entity-relationship diagrams, define table structures, indexing strategies, and establish rules for data normalization while ensuring the new model addresses current limitations and accommodates future growth.', 'design', 'high', '2025-06-25', NULL, current_timestamp, current_timestamp),
('task_303', 'proj_003', NULL, 'Migration Scripts', 'Develop comprehensive migration scripts to transform and transfer data from the legacy database to the new system. Include data validation, transformation logic, and error handling to ensure data integrity during the migration process while maintaining relationships between different data entities.', 'development', 'high', '2025-07-10', NULL, current_timestamp, current_timestamp),
('task_304', 'proj_003', NULL, 'Testing', 'Conduct thorough testing of the migration process including data validation, performance testing, and application compatibility testing. Create test scenarios that simulate real-world conditions and verify that all data has been correctly migrated with proper relationships and constraints preserved.', 'testing', 'high', '2025-07-20', NULL, current_timestamp, current_timestamp),
('task_305', 'proj_003', NULL, 'Deployment', 'Execute the database migration in the production environment following the established migration plan. Implement monitoring tools to track the migration progress, handle any issues that arise during deployment, and verify data integrity after completion before officially cutting over to the new database system.', 'deployment', 'high', '2025-07-30', NULL, current_timestamp, current_timestamp),

-- Project 4: API Integration - Tasks
('task_401', 'proj_004', NULL, 'Research and Planning', 'Analyze integration requirements, evaluate available APIs, and design an integration architecture that meets business needs. Document authentication methods, data formats, rate limits, and establish a clear understanding of the API capabilities and limitations to inform the integration approach.', 'research', 'medium', '2025-01-10', '2025-01-15', current_timestamp, current_timestamp),
('task_402', 'proj_004', NULL, 'API Documentation', 'Create comprehensive documentation for both the external APIs being integrated and the integration interfaces we are developing. Include endpoint descriptions, request/response formats, authentication requirements, error codes, and usage examples to guide developers working with these integrations.', 'documentation', 'medium', '2025-01-20', '2025-01-22', current_timestamp, current_timestamp),
('task_403', 'proj_004', NULL, 'Integration Development', 'Implement the API integration code including authentication handling, request/response processing, error handling, and retry mechanisms. Develop abstraction layers to shield the application from API changes and create monitoring points to track integration health and performance metrics.', 'development', 'high', '2025-01-30', '2025-02-05', current_timestamp, current_timestamp),
('task_404', 'proj_004', NULL, 'Testing', 'Conduct integration testing to verify correct API communication, data transformation, and error handling. Test edge cases including network failures, API downtime, rate limiting scenarios, and validate that the application responds appropriately in all situations while maintaining data consistency.', 'testing', 'high', '2025-02-10', '2025-02-12', current_timestamp, current_timestamp),
('task_405', 'proj_004', NULL, 'Deployment', 'Deploy the API integration to the production environment with proper monitoring and alerting in place. Implement a staged rollout strategy to minimize risks, monitor initial interactions with the external APIs, and establish processes for handling API changes or disruptions in the future.', 'deployment', 'high', '2025-02-15', '2025-02-15', current_timestamp, current_timestamp),

-- Project 5: Dashboard Analytics - Tasks
('task_501', 'proj_005', NULL, 'Research and Planning', 'Identify key metrics and analytics requirements by interviewing stakeholders and analyzing business objectives. Define dashboard user personas, usage patterns, and specific analytics needs to ensure the dashboard provides actionable insights and supports data-driven decision making across different organizational roles.', 'research', 'high', '2025-08-10', NULL, current_timestamp, current_timestamp),
('task_502', 'proj_005', NULL, 'Data Modeling', 'Design the data structures needed to support the analytics dashboard including aggregation methods, calculation models, and data transformation rules. Create efficient data schemas optimized for analytical queries while maintaining reasonable refresh rates and minimal impact on source systems.', 'design', 'medium', '2025-08-25', NULL, current_timestamp, current_timestamp),
('task_503', 'proj_005', NULL, 'Dashboard Development', 'Develop the core dashboard framework including user interface components, navigation system, and configuration options. Implement user preferences, layout customization, and responsive design to provide an intuitive experience across different devices and screen sizes for accessing analytics data.', 'development', 'high', '2025-09-15', NULL, current_timestamp, current_timestamp),
('task_504', 'proj_005', NULL, 'Data Visualization', 'Create interactive data visualizations including charts, graphs, maps, and tables to represent complex data in an easily digestible format. Implement filtering, drill-down capabilities, and comparative views that help users explore data relationships and identify trends or anomalies in the metrics.', 'development', 'high', '2025-10-01', NULL, current_timestamp, current_timestamp),
('task_505', 'proj_005', NULL, 'Testing', 'Conduct comprehensive testing of the dashboard including data accuracy verification, performance testing under various data volumes, and usability testing with actual end users. Validate that calculations are correct, visualizations accurately represent the underlying data, and the system remains responsive under expected load.', 'testing', 'medium', '2025-10-15', NULL, current_timestamp, current_timestamp),
('task_506', 'proj_005', NULL, 'Deployment', 'Deploy the analytics dashboard to production with proper user training and documentation to ensure successful adoption. Set up monitoring for dashboard performance, establish a feedback mechanism for users, and create a maintenance plan for regular updates and enhancements based on user feedback.', 'deployment', 'high', '2025-11-01', NULL, current_timestamp, current_timestamp);

-- Add subtasks for a few more tasks
INSERT INTO tasks (id, project_id, parent_task_id, title, description, label, priority, target_date, completed_at, created_at, updated_at) 
VALUES 
-- Subtasks for Project 3 - Migration Scripts
('task_303_1', 'proj_003', 'task_303', 'Create schema migration', 'Develop scripts to create the new database schema including tables, views, stored procedures, and functions. Include proper dependencies and constraints to ensure data integrity while optimizing the structure for the specific database engine being used.', 'development', 'high', '2025-07-01', NULL, current_timestamp, current_timestamp),
('task_303_2', 'proj_003', 'task_303', 'Create data migration', 'Implement scripts for extracting, transforming, and loading data from the old schema to the new one. Handle data type conversions, address normalization changes, and include validation steps to ensure data quality during the migration process.', 'development', 'high', '2025-07-05', NULL, current_timestamp, current_timestamp),
('task_303_3', 'proj_003', 'task_303', 'Test migrations', 'Execute and validate migration scripts in a controlled environment to verify proper functioning and data integrity. Compare record counts, run data validation queries, and verify that all business rules and constraints are enforced correctly in the new schema.', 'testing', 'high', '2025-07-08', NULL, current_timestamp, current_timestamp),

-- Subtasks for Project 5 - Dashboard Development
('task_503_1', 'proj_005', 'task_503', 'Create dashboard layout', 'Design and implement the main dashboard layout including navigation, panels, widget containers, and responsive grid system. Consider different screen sizes and establish consistent spacing, alignment, and visual hierarchy to create an intuitive user interface.', 'design', 'medium', '2025-09-01', NULL, current_timestamp, current_timestamp),
('task_503_2', 'proj_005', 'task_503', 'Implement data fetching', 'Develop robust data retrieval mechanisms including API clients, caching strategies, and error handling for dashboard components. Implement efficient loading patterns, progress indicators, and fallback states to ensure a smooth user experience even when data is loading or temporarily unavailable.', 'development', 'high', '2025-09-05', NULL, current_timestamp, current_timestamp),
('task_503_3', 'proj_005', 'task_503', 'Create dashboard components', 'Build reusable dashboard widgets and components such as metric cards, trend indicators, data tables, and various chart types. Ensure components are configurable, properly documented, and follow consistent design patterns for ease of maintenance and future extension.', 'development', 'high', '2025-09-10', NULL, current_timestamp, current_timestamp),
('task_503_4', 'proj_005', 'task_503', 'Implement interactivity', 'Add interactive features to the dashboard including filtering, sorting, drill-down capabilities, and customizable views. Implement efficient state management to ensure that user interactions are responsive and that filter changes propagate correctly across related dashboard components.', 'development', 'medium', '2025-09-12', NULL, current_timestamp, current_timestamp);
